package grpc

import (
	"context"

	"google.golang.org/grpc"

	"github.com/bastion/tracker/internal/models"
)

// TrackerServiceServer is the interface generated by hand (no protoc required).
type TrackerServiceServer interface {
	SubmitEvent(context.Context, *models.BastionEvent) (*models.SubmitResponse, error)
	SubmitBatchEvents(context.Context, *models.BatchEventRequest) (*models.BatchResponse, error)
	// QueryEvents streams historical events matching the filter (server-streaming, SRS §6.2).
	QueryEvents(*models.QueryRequest, grpc.ServerStream) error
	GetTrace(context.Context, *models.TraceRequest) (*models.TraceResponse, error)
	GetLineage(context.Context, *models.LineageRequest) (*models.LineageResponse, error)
	GetIncidents(context.Context, *models.IncidentRequest) (*models.IncidentResponse, error)
	Health(context.Context, *models.HealthRequest) (*models.HealthStatus, error)
	StreamEvents(*models.StreamEventsRequest, grpc.ServerStream) error
}

// UnimplementedTrackerServiceServer returns UNIMPLEMENTED for all methods.
type UnimplementedTrackerServiceServer struct{}

func (UnimplementedTrackerServiceServer) SubmitEvent(context.Context, *models.BastionEvent) (*models.SubmitResponse, error) {
	return nil, nil
}
func (UnimplementedTrackerServiceServer) SubmitBatchEvents(context.Context, *models.BatchEventRequest) (*models.BatchResponse, error) {
	return nil, nil
}
func (UnimplementedTrackerServiceServer) QueryEvents(*models.QueryRequest, grpc.ServerStream) error {
	return nil
}
func (UnimplementedTrackerServiceServer) GetTrace(context.Context, *models.TraceRequest) (*models.TraceResponse, error) {
	return nil, nil
}
func (UnimplementedTrackerServiceServer) GetLineage(context.Context, *models.LineageRequest) (*models.LineageResponse, error) {
	return nil, nil
}
func (UnimplementedTrackerServiceServer) GetIncidents(context.Context, *models.IncidentRequest) (*models.IncidentResponse, error) {
	return nil, nil
}
func (UnimplementedTrackerServiceServer) Health(context.Context, *models.HealthRequest) (*models.HealthStatus, error) {
	return nil, nil
}
func (UnimplementedTrackerServiceServer) StreamEvents(*models.StreamEventsRequest, grpc.ServerStream) error {
	return nil
}

// RegisterTrackerServiceServer registers the server implementation with gRPC.
func RegisterTrackerServiceServer(s *grpc.Server, srv TrackerServiceServer) {
	s.RegisterService(&trackerServiceDesc, srv)
}

var trackerServiceDesc = grpc.ServiceDesc{
	ServiceName: "bastion.tracker.v1.TrackerService",
	HandlerType: (*TrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "SubmitEvent", Handler: submitEventHandler},
		{MethodName: "SubmitBatchEvents", Handler: submitBatchHandler},
		{MethodName: "GetTrace", Handler: getTraceHandler},
		{MethodName: "GetLineage", Handler: getLineageHandler},
		{MethodName: "GetIncidents", Handler: getIncidentsHandler},
		{MethodName: "Health", Handler: healthHandler},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryEvents",
			Handler:       queryEventsHandler,
			ServerStreams: true,
			ClientStreams: false,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       streamEventsHandler,
			ServerStreams: true,
			ClientStreams: false,
		},
	},
}

// ─── Unary handlers ───────────────────────────────────────────────────────────

func submitEventHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	var req models.BastionEvent
	if err := dec(&req); err != nil {
		return nil, err
	}
	return srv.(TrackerServiceServer).SubmitEvent(ctx, &req)
}

func submitBatchHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	var req models.BatchEventRequest
	if err := dec(&req); err != nil {
		return nil, err
	}
	return srv.(TrackerServiceServer).SubmitBatchEvents(ctx, &req)
}

func queryEventsHandler(srv interface{}, stream grpc.ServerStream) error {
	var req models.QueryRequest
	if err := stream.RecvMsg(&req); err != nil {
		return err
	}
	return srv.(TrackerServiceServer).QueryEvents(&req, stream)
}

func getTraceHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	var req models.TraceRequest
	if err := dec(&req); err != nil {
		return nil, err
	}
	return srv.(TrackerServiceServer).GetTrace(ctx, &req)
}

func getLineageHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	var req models.LineageRequest
	if err := dec(&req); err != nil {
		return nil, err
	}
	return srv.(TrackerServiceServer).GetLineage(ctx, &req)
}

func getIncidentsHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	var req models.IncidentRequest
	if err := dec(&req); err != nil {
		return nil, err
	}
	return srv.(TrackerServiceServer).GetIncidents(ctx, &req)
}

func healthHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	var req models.HealthRequest
	if err := dec(&req); err != nil {
		return nil, err
	}
	return srv.(TrackerServiceServer).Health(ctx, &req)
}

// ─── Streaming handler ────────────────────────────────────────────────────────

func streamEventsHandler(srv interface{}, stream grpc.ServerStream) error {
	var req models.StreamEventsRequest
	if err := stream.RecvMsg(&req); err != nil {
		return err
	}
	return srv.(TrackerServiceServer).StreamEvents(&req, stream)
}
